In [1]:
from data_loader import *
num_epochs = 1           # Number of full passes through the dataset
batch_size = 16          # Number of samples in each minibatch
learning_rate = 0.001  

train_loader, val_loader, test_loader = create_split_loaders(batch_size,shuffle=True, show_sample=False)
print(train_loader.dataset.input_data.shape) 

[27 81 82 ... 67 76 66]
[81 82 63 ... 76 66 29]
[27 81 82 ... 67 76 66]
[81 82 63 ... 76 66 29]
[27 81 82 ... 67 76 66]
[81 82 63 ... 76 66 29]
(3799, 100)


In [2]:
# Setup: initialize the hyperparameters/variables
num_epochs = 1           # Number of full passes through the dataset
batch_size = 16          # Number of samples in each minibatch
learning_rate = 0.001  
use_cuda=0
# #TODO: Convert to Tensor - you can later add other transformations, such as Scaling here
# transform = transforms.Compose(______)


# # Check if your system supports CUDA
# use_cuda = torch.cuda.is_available()

# Setup GPU optimization if CUDA is supported
if use_cuda:
    computing_device = torch.device("cuda")
    extras = {"num_workers": 1, "pin_memory": True}
    print("CUDA is supported")
else: # Otherwise, train on the CPU
    computing_device = torch.device("cpu")
    extras = False
    print("CUDA NOT supported")

# Setup the training, validation, and testing dataloaders
train_loader, val_loader, test_loader = create_split_loaders(batch_size,shuffle=False, show_sample=False,extras=extras)

# # Instantiate a BasicCNN to run on the GPU or CPU based on CUDA support
# model = BasicCNN()
# model = model.to(computing_device)
# print("Model on CUDA?", next(model.parameters()).is_cuda)

# #TODO: Define the loss criterion and instantiate the gradient descent optimizer
# criterion = ______ #TODO - loss criteria are defined in the torch.nn package

# #TODO: Instantiate the gradient descent optimizer - use Adam optimizer with default parameters
# optimizer = ______ #TODO - optimizers are defined in the torch.optim package

CUDA NOT supported
[27 81 82 ... 67 76 66]
[81 82 63 ... 76 66 29]
[27 81 82 ... 67 76 66]
[81 82 63 ... 76 66 29]
[27 81 82 ... 67 76 66]
[81 82 63 ... 76 66 29]


In [3]:
# Track the loss across training
total_loss = []
avg_minibatch_loss = []

# Begin training procedure
for epoch in range(num_epochs):

    N = 50
    N_minibatch_loss = 0.0    

    # Get the next minibatch of images, labels for training
    for minibatch_count, (images, labels) in enumerate(train_loader, 0):
        
        print(images.shape,images.permute(1,0,2).shape)
        print(minibatch_count)
        images=images.permute(1,0,2)
        labels=labels.permute(1,0,2)
        
#         # Put the minibatch data in CUDA Tensors and run on the GPU if supported
#         images, labels = images.to(computing_device), labels.to(computing_device)

#         # Zero out the stored gradient (buffer) from the previous iteration
#         optimizer.zero_grad()

#         # Perform the forward pass through the network and compute the loss
#         outputs = model(images)
#         loss = criterion(outputs, labels)
        
#         # Automagically compute the gradients and backpropagate the loss through the network
#         loss.backward()

#         # Update the weights
#         optimizer.step()

#         # Add this iteration's loss to the total_loss
#         total_loss.append(loss.item())
#         N_minibatch_loss += loss
        
#         #TODO: Implement cross-validation
        
#         if minibatch_count % N == 0:    
            
#             # Print the loss averaged over the last N mini-batches    
#             N_minibatch_loss /= N
#             print('Epoch %d, average minibatch %d loss: %.3f' %
#                 (epoch + 1, minibatch_count, N_minibatch_loss))
            
#             # Add the averaged loss over N minibatches and reset the counter
#             avg_minibatch_loss.append(N_minibatch_loss)
#             N_minibatch_loss = 0.0

#     print("Finished", epoch + 1, "epochs of training")
# print("Training complete after", epoch, "epochs")

torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
0
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
1
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
2
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
3
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
4
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
5
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
6
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
7
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
8
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
9
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
10
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
11
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
12
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
13
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
14
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
15
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
16
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
17
torch.Size([16, 100,

torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
156
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
157
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
158
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
159
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
160
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
161
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
162
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
163
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
164
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
165
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
166
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
167
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
168
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
169
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
170
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
171
torch.Size([16, 100, 93]) torch.Size([100, 16, 93])
172
torch.Size([16, 100, 93]) torch.Size([100, 16, 9